version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: 'circleci/node:8.9'
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'dev-dependencies-{{ checksum "yarn.lock" }}'
            - dev-dependencies-
      - run: yarn install --silent
      - save_cache:
          paths:
            - node_modules
          key: 'dev-dependencies-{{ checksum "yarn.lock" }}'

  test:
    working_directory: ~/repo
    docker:
      - image: 'circleci/node:8.9'
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'dev-dependencies-{{ checksum "yarn.lock" }}'
            - dev-dependencies-
      - run: yarn run mocha

  prod_deps:
    working_directory: ~/repo
    docker:
      - image: 'circleci/node:8.9'
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'prod-dependencies-{{ checksum "yarn.lock" }}'
            - prod-dependencies-
      - run: yarn install --production --silent
      - save_cache:
          paths:
            - node_modules
          key: 'prod-dependencies-{{ checksum "yarn.lock" }}'

  deploy:
    working_directory: ~/repo
    docker:
      - image: 'google/cloud-sdk:slim'
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS: "/tmp/gcloud-service-key.json"
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'prod-dependencies-{{ checksum "yarn.lock" }}'
            - prod-dependencies-
      - run: 'touch $GOOGLE_APPLICATION_CREDENTIALS'
      - run: 'echo $GCLOUD_SA_203 | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS'
      - run: 'gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS'
      - run: 'gcloud config set project $GCLOUD_PROJECT'
      - run: 'gcloud -q app deploy app.yaml'

  migrate:
    working_directory: ~/repo
    docker:
      - image: 'ankemp/gcloud-sqlproxy-node:0.1.0'
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS: "/tmp/gcloud-service-key.json"
      - INSTANCE_CONNECTION_NAME: "br-history-188417:us-central1:br-db"
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'dev-dependencies-{{ checksum "yarn.lock" }}'
            - dev-dependencies-
      - run: 'touch $GOOGLE_APPLICATION_CREDENTIALS'
      - run: 'echo $GCLOUD_SA_203 | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS'
      - run: 'gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS'
      - run: 'gcloud config set project $GCLOUD_PROJECT'
      - run: '/usr/local/bin/cloud_sql_proxy -instances=$INSTANCE_CONNECTION_NAME=tcp:3306'
      - run: 'npm run migration:run'

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - prod_deps:
          filters:
            branches:
              only: master
          requires:
            - test
      - deploy:
          requires:
            - prod_deps
